version: '3.8'

services:
  audio-server:
    image: dingguoping55/audio-server:1.61
    container_name: audio-server
    ports:
      - "8000:8000"
    volumes:
      - ./voice:/app/voice
      - ./logs:/app/logs
    environment:
      - PORT=8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 3s
      retries: 3 